### ISSUE TITLE
Important issue you might wanna look at...

### ISSUE THREAD

**Issue by TraytenTurner** [BruhTurner/campfire-song#5]
I hate this song... I had to learn it in Daycare. They would sing it during nap time for hours, it was torture! Please take this down so you don't trigger my PTSD...

**Comment by Quinaris** [comment]
That sounds like a you problem

**Comment by BruhTurner** [comment]
no

**Comment by BruhTurner** [comment]
![maxresdefault](https://user-images.githubusercontent.com/60892592/75372106-90ba8f80-588d-11ea-8783-f029aa38462d.jpg)

**Comment by Quinaris** [comment]
Heresy of the highest order
